version: '3'
services:
  minecraft-server:
    image: minecraftsv:1.0
    env_file:
      - .env
    container_name: mineteste
    ports:
      - "9350:25565"
      - "25575:25575"
    volumes:
      - ./minetest:/data
      - ./mods:/data/mods
      - ./script:/data/script
      - ./config/prop.prop:/data/server/mineteste/server.properties

    entrypoint: ["bash", "./script/inicia.sh"]
    restart: unless-stopped
volumes:
  minetest: {}
