version: '3.6'

services:
    xoce:
        image: ezka77/xen-orchestra-ce:5.135
        ports:
            - "9635:8000"
        depends_on:
            - redis
        environment:
            - DEBUG=xo:main
            - NODE_ENV=production
            - XOA_PLAN=5
            - privileged=true
            - useForwardedHeaders=['127.0.0.1']
        cap_add:
          - SYS_ADMIN
        devices:
            - "/dev/fuse:/dev/fuse"
            - "/dev/loop-control:/dev/loop-control"
        volumes:
            - ./xo-data:/storage
        logging: &default_logging
            driver: "json-file"
            options:
                max-size: "1M"
                max-file: "2"
        networks:
            - xoce-net
            - redis-net 
            - nginx

        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.hostname == zeus]

    redis:
        image: redis:alpine
        command: redis-server --appendonly yes
        volumes:
            - ./redis-data:/data
        logging:
            <<: *default_logging
        networks:
            - redis-net
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.hostname == zeus]

networks:
    xoce-net:
        driver: overlay

    redis-net:
        driver: overlay

    nginx:
        external:
            name: nginx