version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ce:16.7.5-ce.0
    volumes:
      - ./gitlab-data/data:/var/opt/gitlab
      - ./gitlab-data/logs:/var/log/gitlab
      - ./gitlab-data/config:/etc/gitlab
    shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/etc/gitlab/gitlab.rb')"
    networks:
      - gitlab
      - nginx
    
    healthcheck:
      interval: 6m30s
    
    deploy:
      placement:
        constraints:
          - node.hostname == gaia

      update_config:
        parallelism: 1
        delay: 10s

      restart_policy:
        condition: any

configs:
  gitlab:
    file: ./gitlab.rb

networks:
  gitlab:
    driver: overlay

  nginx:
    external:
      name: nginx